### ISSUE TITLE
Bump node-sass

### ISSUE THREAD

**Issue by sanderjson** [spiegelgraphics/nobel-laureates#1]
Wow this is amazing! Thanks 🤩😎

Had to bump node-sass for installation. For anyone else on Node v18+  delete `node-sass` from `package.json`, install dependencies, and then reinstall `node-sass`.

**Comment by konstantinblaesi** [comment]
Great tip I just ran into this (node v16.14.0, fedora 36) after watching the [great talk from matthias](https://www.youtube.com/watch?v=5focjEPJUJs), so in summary these commands will do

Install and build once
> npm uninstall node-sass
> npm install node-sass
> npm run build

Start the webserver
> npm start

Visit http://localhost:8080

**Comment by higsch** [comment]
Cool, thanks for pointing that out and your immediate solution!
